site_name: HPC Client
site_description: Student and researcher guide for submitting jobs to the HPC Scheduler

theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - navigation.indexes

nav:
  - CARES HPC Scheduler:
      - Introduction: index.md
      - Docker Images: docker.md
      - Datasets: datasets.md
      - Outputs: outputs.md
  - HPC-Client: 
      - Overview: hpc-client/index.md
      - Installation: hpc-client/installation.md
      - Python API: hpc-client/python_api.md


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - tables

plugins:
  - search
  - glightbox